server:
  port: 5555

spring:
  activemq:
    broker-url: tcp://120.27.111.97:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false：表示 queue，true：表示topic

myTopic: springboot-activemq-topic